[soil]
static = true

[[soil.microbial_group_definition]]
name = "bacteria"
taxonomic_group = "bacteria"
max_uptake_rate_labile_C = 0.04
activation_energy_uptake_rate = 47000
half_sat_labile_C_uptake = 0.364
activation_energy_uptake_saturation = 30000
max_uptake_rate_ammonium = 0.005
half_sat_ammonium_uptake = 0.02275
max_uptake_rate_nitrate = 0.0005
half_sat_nitrate_uptake = 0.02275
max_uptake_rate_labile_p = 0.0025
half_sat_labile_p_uptake = 0.02275
turnover_rate = 0.005
activation_energy_turnover = 20000
reference_temperature = 12.0
c_n_ratio = 5.2
c_p_ratio = 16

[soil.microbial_group_definition.enzyme_production]
pom = 0.005
maom = 0.005

[[soil.microbial_group_definition]]
name = "saprotrophic_fungi"
taxonomic_group = "fungi"
max_uptake_rate_labile_C = 0.04
activation_energy_uptake_rate = 47000
half_sat_labile_C_uptake = 0.364
activation_energy_uptake_saturation = 30000
max_uptake_rate_ammonium = 0.005
half_sat_ammonium_uptake = 0.02275
max_uptake_rate_nitrate = 0.0005
half_sat_nitrate_uptake = 0.02275
max_uptake_rate_labile_p = 0.0025
half_sat_labile_p_uptake = 0.02275
turnover_rate = 0.005
activation_energy_turnover = 20000
reference_temperature = 12.0
c_n_ratio = 6.5
c_p_ratio = 40.0

[soil.microbial_group_definition.enzyme_production]
pom = 0.005
maom = 0.005

[[soil.microbial_group_definition]]
name = "arbuscular_mycorrhiza"
taxonomic_group = "fungi"
max_uptake_rate_labile_C = 0.04
activation_energy_uptake_rate = 47000
half_sat_labile_C_uptake = 0.364
activation_energy_uptake_saturation = 30000
max_uptake_rate_ammonium = 0.005
half_sat_ammonium_uptake = 0.02275
max_uptake_rate_nitrate = 0.0005
half_sat_nitrate_uptake = 0.02275
max_uptake_rate_labile_p = 0.0025
half_sat_labile_p_uptake = 0.02275
turnover_rate = 0.005
activation_energy_turnover = 20000
reference_temperature = 12.0
c_n_ratio = 18.0
c_p_ratio = 120.0

[soil.microbial_group_definition.enzyme_production]
pom = 0.0
maom = 0.0

[[soil.microbial_group_definition]]
name = "ectomycorrhiza"
taxonomic_group = "fungi"
max_uptake_rate_labile_C = 0.04
activation_energy_uptake_rate = 47000
half_sat_labile_C_uptake = 0.364
activation_energy_uptake_saturation = 30000
max_uptake_rate_ammonium = 0.005
half_sat_ammonium_uptake = 0.02275
max_uptake_rate_nitrate = 0.0005
half_sat_nitrate_uptake = 0.02275
max_uptake_rate_labile_p = 0.0025
half_sat_labile_p_uptake = 0.02275
turnover_rate = 0.005
activation_energy_turnover = 20000
reference_temperature = 12.0
c_n_ratio = 18.0
c_p_ratio = 120.0

[soil.microbial_group_definition.enzyme_production]
pom = 0.02
maom = 0.02

[[soil.enzyme_class_definition]]
source = "bacteria"
substrate = "pom"
maximum_rate = 60.0
half_saturation_constant = 70.0
activation_energy_rate = 37000
activation_energy_saturation = 30000
reference_temperature = 12.0
turnover_rate = 0.024
c_n_ratio = 5.2
c_p_ratio = 16

[[soil.enzyme_class_definition]]
source = "bacteria"
substrate = "maom"
maximum_rate = 24.0
half_saturation_constant = 350.0
activation_energy_rate = 47000
activation_energy_saturation = 30000
reference_temperature = 12.0
turnover_rate = 0.024
c_n_ratio = 5.2
c_p_ratio = 16

[[soil.enzyme_class_definition]]
source = "fungi"
substrate = "pom"
maximum_rate = 120.0
half_saturation_constant = 35.0
activation_energy_rate = 37000
activation_energy_saturation = 30000
reference_temperature = 12.0
turnover_rate = 0.024
c_n_ratio = 6.5
c_p_ratio = 40.0

[[soil.enzyme_class_definition]]
source = "fungi"
substrate = "maom"
maximum_rate = 48.0
half_saturation_constant = 175.0
activation_energy_rate = 47000
activation_energy_saturation = 30000
reference_temperature = 12.0
turnover_rate = 0.024
c_n_ratio = 6.5
c_p_ratio = 40.0

[[core.data.variable]]
file_path = "/Users/lin/Code/ve_example/data/example_plant_data.nc"
var_name = "plant_cohorts_n"

[[core.data.variable]]
file_path = "/Users/lin/Code/ve_example/data/example_plant_data.nc"
var_name = "plant_cohorts_pft"

[[core.data.variable]]
file_path = "/Users/lin/Code/ve_example/data/example_plant_data.nc"
var_name = "plant_cohorts_cell_id"

[[core.data.variable]]
file_path = "/Users/lin/Code/ve_example/data/example_plant_data.nc"
var_name = "plant_cohorts_dbh"

[[core.data.variable]]
file_path = "/Users/lin/Code/ve_example/data/example_plant_data.nc"
var_name = "downward_shortwave_radiation"

[[core.data.variable]]
file_path = "/Users/lin/Code/ve_example/data/example_plant_data.nc"
var_name = "subcanopy_vegetation_biomass"

[[core.data.variable]]
file_path = "/Users/lin/Code/ve_example/data/example_plant_data.nc"
var_name = "subcanopy_seedbank_biomass"

[[core.data.variable]]
file_path = "/Users/lin/Code/ve_example/data/example_climate_data.nc"
var_name = "air_temperature_ref"

[[core.data.variable]]
file_path = "/Users/lin/Code/ve_example/data/example_climate_data.nc"
var_name = "relative_humidity_ref"

[[core.data.variable]]
file_path = "/Users/lin/Code/ve_example/data/example_climate_data.nc"
var_name = "atmospheric_pressure_ref"

[[core.data.variable]]
file_path = "/Users/lin/Code/ve_example/data/Low_0397.nc"
var_name = "precipitation"

[[core.data.variable]]
file_path = "/Users/lin/Code/ve_example/data/example_climate_data.nc"
var_name = "atmospheric_co2_ref"

[[core.data.variable]]
file_path = "/Users/lin/Code/ve_example/data/example_climate_data.nc"
var_name = "mean_annual_temperature"

[[core.data.variable]]
file_path = "/Users/lin/Code/ve_example/data/example_climate_data.nc"
var_name = "wind_speed_ref"

[[core.data.variable]]
file_path = "/Users/lin/Code/ve_example/data/example_elevation_data.nc"
var_name = "elevation"

[[core.data.variable]]
file_path = "/Users/lin/Code/ve_example/data/example_soil_data.nc"
var_name = "pH"

[[core.data.variable]]
file_path = "/Users/lin/Code/ve_example/data/example_soil_data.nc"
var_name = "bulk_density"

[[core.data.variable]]
file_path = "/Users/lin/Code/ve_example/data/example_soil_data.nc"
var_name = "clay_fraction"

[[core.data.variable]]
file_path = "/Users/lin/Code/ve_example/data/example_soil_data.nc"
var_name = "soil_c_pool_lmwc"

[[core.data.variable]]
file_path = "/Users/lin/Code/ve_example/data/example_soil_data.nc"
var_name = "soil_c_pool_maom"

[[core.data.variable]]
file_path = "/Users/lin/Code/ve_example/data/example_soil_data.nc"
var_name = "soil_c_pool_bacteria"

[[core.data.variable]]
file_path = "/Users/lin/Code/ve_example/data/example_soil_data.nc"
var_name = "soil_c_pool_saprotrophic_fungi"

[[core.data.variable]]
file_path = "/Users/lin/Code/ve_example/data/example_soil_data.nc"
var_name = "soil_c_pool_arbuscular_mycorrhiza"

[[core.data.variable]]
file_path = "/Users/lin/Code/ve_example/data/example_soil_data.nc"
var_name = "soil_c_pool_ectomycorrhiza"

[[core.data.variable]]
file_path = "/Users/lin/Code/ve_example/data/example_soil_data.nc"
var_name = "soil_c_pool_pom"

[[core.data.variable]]
file_path = "/Users/lin/Code/ve_example/data/example_soil_data.nc"
var_name = "soil_c_pool_necromass"

[[core.data.variable]]
file_path = "/Users/lin/Code/ve_example/data/example_soil_data.nc"
var_name = "soil_enzyme_pom_bacteria"

[[core.data.variable]]
file_path = "/Users/lin/Code/ve_example/data/example_soil_data.nc"
var_name = "soil_enzyme_maom_bacteria"

[[core.data.variable]]
file_path = "/Users/lin/Code/ve_example/data/example_soil_data.nc"
var_name = "soil_enzyme_pom_fungi"

[[core.data.variable]]
file_path = "/Users/lin/Code/ve_example/data/example_soil_data.nc"
var_name = "soil_enzyme_maom_fungi"

[[core.data.variable]]
file_path = "/Users/lin/Code/ve_example/data/example_soil_data.nc"
var_name = "soil_n_pool_don"

[[core.data.variable]]
file_path = "/Users/lin/Code/ve_example/data/example_soil_data.nc"
var_name = "soil_n_pool_particulate"

[[core.data.variable]]
file_path = "/Users/lin/Code/ve_example/data/example_soil_data.nc"
var_name = "soil_n_pool_necromass"

[[core.data.variable]]
file_path = "/Users/lin/Code/ve_example/data/example_soil_data.nc"
var_name = "soil_n_pool_maom"

[[core.data.variable]]
file_path = "/Users/lin/Code/ve_example/data/example_soil_data.nc"
var_name = "soil_n_pool_ammonium"

[[core.data.variable]]
file_path = "/Users/lin/Code/ve_example/data/example_soil_data.nc"
var_name = "soil_n_pool_nitrate"

[[core.data.variable]]
file_path = "/Users/lin/Code/ve_example/data/example_soil_data.nc"
var_name = "soil_p_pool_dop"

[[core.data.variable]]
file_path = "/Users/lin/Code/ve_example/data/example_soil_data.nc"
var_name = "soil_p_pool_particulate"

[[core.data.variable]]
file_path = "/Users/lin/Code/ve_example/data/example_soil_data.nc"
var_name = "soil_p_pool_necromass"

[[core.data.variable]]
file_path = "/Users/lin/Code/ve_example/data/example_soil_data.nc"
var_name = "soil_p_pool_maom"

[[core.data.variable]]
file_path = "/Users/lin/Code/ve_example/data/example_soil_data.nc"
var_name = "soil_p_pool_primary"

[[core.data.variable]]
file_path = "/Users/lin/Code/ve_example/data/example_soil_data.nc"
var_name = "soil_p_pool_secondary"

[[core.data.variable]]
file_path = "/Users/lin/Code/ve_example/data/example_soil_data.nc"
var_name = "soil_p_pool_labile"

[[core.data.variable]]
file_path = "/Users/lin/Code/ve_example/data/example_litter_data.nc"
var_name = "litter_pool_above_metabolic"

[[core.data.variable]]
file_path = "/Users/lin/Code/ve_example/data/example_litter_data.nc"
var_name = "litter_pool_above_structural"

[[core.data.variable]]
file_path = "/Users/lin/Code/ve_example/data/example_litter_data.nc"
var_name = "litter_pool_woody"

[[core.data.variable]]
file_path = "/Users/lin/Code/ve_example/data/example_litter_data.nc"
var_name = "litter_pool_below_metabolic"

[[core.data.variable]]
file_path = "/Users/lin/Code/ve_example/data/example_litter_data.nc"
var_name = "litter_pool_below_structural"

[[core.data.variable]]
file_path = "/Users/lin/Code/ve_example/data/example_litter_data.nc"
var_name = "lignin_above_structural"

[[core.data.variable]]
file_path = "/Users/lin/Code/ve_example/data/example_litter_data.nc"
var_name = "lignin_woody"

[[core.data.variable]]
file_path = "/Users/lin/Code/ve_example/data/example_litter_data.nc"
var_name = "lignin_below_structural"

[[core.data.variable]]
file_path = "/Users/lin/Code/ve_example/data/example_litter_data.nc"
var_name = "c_n_ratio_above_metabolic"

[[core.data.variable]]
file_path = "/Users/lin/Code/ve_example/data/example_litter_data.nc"
var_name = "c_n_ratio_above_structural"

[[core.data.variable]]
file_path = "/Users/lin/Code/ve_example/data/example_litter_data.nc"
var_name = "c_n_ratio_woody"

[[core.data.variable]]
file_path = "/Users/lin/Code/ve_example/data/example_litter_data.nc"
var_name = "c_n_ratio_below_metabolic"

[[core.data.variable]]
file_path = "/Users/lin/Code/ve_example/data/example_litter_data.nc"
var_name = "c_n_ratio_below_structural"

[[core.data.variable]]
file_path = "/Users/lin/Code/ve_example/data/example_litter_data.nc"
var_name = "c_p_ratio_above_metabolic"

[[core.data.variable]]
file_path = "/Users/lin/Code/ve_example/data/example_litter_data.nc"
var_name = "c_p_ratio_above_structural"

[[core.data.variable]]
file_path = "/Users/lin/Code/ve_example/data/example_litter_data.nc"
var_name = "c_p_ratio_woody"

[[core.data.variable]]
file_path = "/Users/lin/Code/ve_example/data/example_litter_data.nc"
var_name = "c_p_ratio_below_metabolic"

[[core.data.variable]]
file_path = "/Users/lin/Code/ve_example/data/example_litter_data.nc"
var_name = "c_p_ratio_below_structural"

[core.data_output_options]
save_initial_state = true
out_path = "/Users/lin/Code/ve_example/out"
save_continuous_data = true
save_final_state = true
save_merged_config = true
out_initial_file_name = "initial_state.nc"
out_continuous_file_name = "all_continuous_data.nc"
out_final_file_name = "final_state.nc"
out_merge_file_name = "l0397.toml"

[core.grid]
grid_type = "square"
cell_area = 8100
cell_nx = 9
cell_ny = 9
xoff = -45.0
yoff = -45.0

[core.timing]
start_date = "2013-01-01"
update_interval = "1 month"
run_length = "2 years"

[core.layers]
soil_layers = [
    -0.25,
    -1.0,
]
canopy_layers = 10
above_canopy_height_offset = 2.0
surface_layer_height = 0.1
subcanopy_layer_height = 1.5

[hydrology]
initial_soil_moisture = 0.5
initial_groundwater_saturation = 0.5
static = false

[abiotic_simple]
static = true

[animal]
static = true

[[animal.functional_groups]]
name = "carnivorous_bird"
taxa = "bird"
diet = "carnivore"
metabolic_type = "endothermic"
reproductive_environment = "terrestrial"
reproductive_type = "iteroparous"
development_type = "direct"
development_status = "adult"
offspring_functional_group = "carnivorous_bird"
excretion_type = "uricotelic"
migration_type = "none"
vertical_occupancy = "ground_canopy"
birth_mass = 0.1
adult_mass = 1.0

[[animal.functional_groups]]
name = "herbivorous_bird"
taxa = "bird"
diet = "herbivore"
metabolic_type = "endothermic"
reproductive_environment = "terrestrial"
reproductive_type = "iteroparous"
development_type = "direct"
development_status = "adult"
offspring_functional_group = "herbivorous_bird"
excretion_type = "uricotelic"
migration_type = "none"
vertical_occupancy = "ground_canopy"
birth_mass = 0.05
adult_mass = 0.5

[[animal.functional_groups]]
name = "carnivorous_mammal"
taxa = "mammal"
diet = "carnivore"
metabolic_type = "endothermic"
reproductive_environment = "terrestrial"
reproductive_type = "iteroparous"
development_type = "direct"
development_status = "adult"
offspring_functional_group = "carnivorous_mammal"
excretion_type = "ureotelic"
migration_type = "none"
vertical_occupancy = "ground"
birth_mass = 4.0
adult_mass = 40.0

[[animal.functional_groups]]
name = "herbivorous_mammal"
taxa = "mammal"
diet = "herbivore"
metabolic_type = "endothermic"
reproductive_environment = "terrestrial"
reproductive_type = "iteroparous"
development_type = "direct"
development_status = "adult"
offspring_functional_group = "herbivorous_mammal"
excretion_type = "ureotelic"
migration_type = "none"
vertical_occupancy = "ground"
birth_mass = 1.0
adult_mass = 10.0

[[animal.functional_groups]]
name = "carnivorous_insect"
taxa = "invertebrate"
diet = "carnivore"
metabolic_type = "ectothermic"
reproductive_environment = "terrestrial"
reproductive_type = "iteroparous"
development_type = "direct"
development_status = "adult"
offspring_functional_group = "carnivorous_insect"
excretion_type = "uricotelic"
migration_type = "none"
vertical_occupancy = "soil_ground_canopy"
birth_mass = 0.001
adult_mass = 0.01

[[animal.functional_groups]]
name = "herbivorous_insect"
taxa = "invertebrate"
diet = "herbivore"
metabolic_type = "ectothermic"
reproductive_environment = "terrestrial"
reproductive_type = "semelparous"
development_type = "direct"
development_status = "adult"
offspring_functional_group = "herbivorous_insect"
excretion_type = "uricotelic"
migration_type = "none"
vertical_occupancy = "soil_ground_canopy"
birth_mass = 0.0005
adult_mass = 0.005

[[animal.functional_groups]]
name = "butterfly"
taxa = "invertebrate"
diet = "herbivore"
metabolic_type = "ectothermic"
reproductive_environment = "terrestrial"
reproductive_type = "semelparous"
development_type = "indirect"
development_status = "adult"
offspring_functional_group = "caterpillar"
excretion_type = "uricotelic"
migration_type = "none"
vertical_occupancy = "ground_canopy"
birth_mass = 0.0005
adult_mass = 0.005

[[animal.functional_groups]]
name = "caterpillar"
taxa = "invertebrate"
diet = "herbivore"
metabolic_type = "ectothermic"
reproductive_environment = "terrestrial"
reproductive_type = "nonreproductive"
development_type = "indirect"
development_status = "larval"
offspring_functional_group = "butterfly"
excretion_type = "uricotelic"
migration_type = "none"
vertical_occupancy = "canopy"
birth_mass = 0.0005
adult_mass = 0.005

[[animal.functional_groups]]
name = "frog"
taxa = "amphibian"
diet = "carnivore"
metabolic_type = "ectothermic"
reproductive_environment = "aquatic"
reproductive_type = "iteroparous"
development_type = "direct"
development_status = "adult"
offspring_functional_group = "frog"
excretion_type = "ureotelic"
migration_type = "none"
vertical_occupancy = "ground"
birth_mass = 0.005
adult_mass = 0.5

[[animal.functional_groups]]
name = "swallow"
taxa = "bird"
diet = "carnivore"
metabolic_type = "endothermic"
reproductive_environment = "terrestrial"
reproductive_type = "iteroparous"
development_type = "direct"
development_status = "adult"
offspring_functional_group = "swallow"
excretion_type = "uricotelic"
migration_type = "seasonal"
vertical_occupancy = "canopy"
birth_mass = 0.005
adult_mass = 0.2

[[animal.functional_groups]]
name = "earthworm"
taxa = "invertebrate"
diet = "herbivore"
metabolic_type = "ectothermic"
reproductive_environment = "terrestrial"
reproductive_type = "iteroparous"
development_type = "direct"
development_status = "adult"
offspring_functional_group = "earthworm"
excretion_type = "uricotelic"
migration_type = "none"
vertical_occupancy = "soil"
birth_mass = 0.0005
adult_mass = 0.005

[litter]
static = true

[plants]
pft_definitions_path = "/Users/lin/Code/ve_example/data/plant_pfts.csv"
static = true

[plants.community_data_export]
required_data = []
cohort_attributes = []
community_canopy_attributes = []
stem_canopy_attributes = []
float_format = "%0.5f"
